### ISSUE TITLE
Add more methods to span

### ISSUE THREAD

**Issue by killercup** [killercup/output-rs#19]
In addition to colors, the termcolor crate [supports](https://docs.rs/termcolor/1.0.4/termcolor/struct.ColorSpec.html) some other styles. Our spans should, too!

- [x] bold
- [x] underline
- [x] intense

**Comment by Hourann** [comment]
can i help?

**Comment by killercup** [comment]
@Hourann absolutely!

Let me try and explain how the `span` component works right now. The currently implemented methods live here:

https://github.com/killercup/output-rs/blob/c60002f0190f16a044eae48250a60562b8ace495/src/components/span.rs#L68-L76

As you can see, they set some fields on the struct to update the internal style. These fields are defined here:

https://github.com/killercup/output-rs/blob/c60002f0190f16a044eae48250a60562b8ace495/src/components/span.rs#L58-L59

When you render a `span`, the `render_for_humans` method gets called. To actually apply the style, it builds a [`ColorSpec`](https://docs.rs/termcolor/1.0.4/termcolor/struct.ColorSpec.html) and tells the internal writer to use it:

https://github.com/killercup/output-rs/blob/c60002f0190f16a044eae48250a60562b8ace495/src/components/span.rs#L79-L82

To add the additonal styling features, you'll need to 1) add the new methods that 2) change new fields and 3) are used in the ColorSpec builder.

To test this, I recommend copying this test:

https://github.com/killercup/output-rs/blob/c60002f0190f16a044eae48250a60562b8ace495/src/components/span.rs#L121-L122

**Comment by Hourann** [comment]
I am considering two kinds of apis, taking bold as an example.
The first one is explicitly takes an bool argument:
```rust
span().bold(true)
```
The second one just think you want to set it to bold when method called
```rust
span().bold()
```
I think the latter is better, because in no case user will call `span().bold(false)`  because it's default behavior.

What's your opinion?

**Comment by killercup** [comment]
Good question! There are two cases to consider.

1. > because in no case user will call span().bold(false) because it's default behavior.

    Hypothetical question: What if you have a function that generates a "common" span style and in one case you want to overwrite the span you got from it to not be bold?

2. The `span!` macro!

  Right now, it assumes methods take a parameter:
   
  https://github.com/killercup/output-rs/blob/c60002f0190f16a044eae48250a60562b8ace495/src/components/span.rs#L12-L13

  So, if you were to write it like `.bold()`, you'd need to change the macro to support that case, too.

Thus, I suggest you go with `span().bold(true)`.

- - - 

I have another, maybe weird proposal. I'm not saying you should do this, but I wanted to mention it:

```rust
enum FontWeight { Regular, Bold }

trait TryIntoFontWeight {
    fn try_into_font_weight(from: Self) -> Result<FontWeight, Error>;
}

// interesting
impl<'a> TryIntoFontWeight for &'a str {
    fn try_into_font_weight(from: &'a str) -> FontWeight {
        match from {
            "regular" => Ok(FontWeight::Regular),
            "bold" => Ok(FontWeight::Bold),
            _ => Err(Error::SomeErrorVariant),
        }
    }
}

// trivial
impl TryIntoFontWeight for FontWeight {
    fn try_into_font_weight(from: FontWeight) -> FontWeight { Ok(from) }
}

// and now use it
impl Span {
    pub fn weight<W: TryIntoFontWeight>(mut self, weight: W) -> Self {
        self.weight = Some(weight.try_into_font_weight()?);
        Ok(self)
    }
}
```
